title: BestOf
description: the best things!
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-include-cache

color_scheme: bird

callouts:
  alternative:
    title: alternative
    color: yellow
  note:
    title: note
    color: blue
  warning:
    title: warning
    color: red
  upcoming:
    title: upcoming
    color: green
  disclaimer:
    title: disclaimer
    color: pink

callouts_opacity: 0.33
  
nav_external_links:
  - title: bestof on GitHub
    url: https://github.com/swarbler/bestof
    hide_icon: false
    opens_in_new_tab: false
  - title: sbird
    url: https://swarbler.github.io
    hide_icon: false
    opens_in_new_tab: true
