title: BestOf
description: the best things!
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-include-cache

color_scheme: bird

callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  purple:
    title: Fun Fact
    color: purple
  
nav_external_links:
  - title: bestof on GitHub
    url: https://github.com/swarbler/bestof
    hide_icon: false
    opens_in_new_tab: false
  - title: sbird
    url: https://swarbler.github.io
    hide_icon: false
    opens_in_new_tab: true
