title: BestOf
description: the best things!
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-include-cache

callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue

aux_links:
  sbird:
    - https://swarbler.github.io

